package com.ejemplo.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;

public class PantallaInicial extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Table table_1;
    @AutoGenerated
    private Button button_1;
    @AutoGenerated
    private TwinColSelect twinColSelect_1;
    @AutoGenerated
    private RichTextArea richTextArea_1;
    @AutoGenerated
    private InlineDateField inlineDateField_1;
    @AutoGenerated
    private TextField textField_1;
    @AutoGenerated
    private Label label_1;

    public AbsoluteLayout getMainLayout() {
        return mainLayout;
    }

    public void setMainLayout(AbsoluteLayout mainLayout) {
        this.mainLayout = mainLayout;
    }

    public Button getButton_1() {
        return button_1;
    }

    public void setButton_1(Button button_1) {
        this.button_1 = button_1;
    }

    public TwinColSelect getTwinColSelect_1() {
        return twinColSelect_1;
    }

    public void setTwinColSelect_1(TwinColSelect twinColSelect_1) {
        this.twinColSelect_1 = twinColSelect_1;
    }

    public Table getTable_1() {
        return table_1;
    }

    public void setTable_1(Table table_1) {
        this.table_1 = table_1;
    }

    public RichTextArea getRichTextArea_1() {
        return richTextArea_1;
    }

    public void setRichTextArea_1(RichTextArea richTextArea_1) {
        this.richTextArea_1 = richTextArea_1;
    }

    public InlineDateField getInlineDateField_1() {
        return inlineDateField_1;
    }

    public void setInlineDateField_1(InlineDateField inlineDateField_1) {
        this.inlineDateField_1 = inlineDateField_1;
    }

    public TextField getTextField_1() {
        return textField_1;
    }

    public void setTextField_1(TextField textField_1) {
        this.textField_1 = textField_1;
    }

    public Label getLabel_1() {
        return label_1;
    }

    public void setLabel_1(Label label_1) {
        this.label_1 = label_1;
    }

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public PantallaInicial() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("130px");
        label_1.setHeight("-1px");
        label_1.setValue("Nombre");
        mainLayout.addComponent(label_1, "top:60.0px;left:70.0px;");

        // textField_1
        textField_1 = new TextField();
        textField_1.setImmediate(false);
        textField_1.setWidth("-1px");
        textField_1.setHeight("-1px");
        textField_1.setMaxLength(15);
        mainLayout.addComponent(textField_1, "top:80.0px;left:70.0px;");

        // inlineDateField_1
        inlineDateField_1 = new InlineDateField();
        inlineDateField_1.setImmediate(false);
        inlineDateField_1.setWidth("-1px");
        inlineDateField_1.setHeight("-1px");
        mainLayout.addComponent(inlineDateField_1, "top:86.0px;left:238.0px;");

        // richTextArea_1
        richTextArea_1 = new RichTextArea();
        richTextArea_1.setImmediate(false);
        richTextArea_1.setWidth("-1px");
        richTextArea_1.setHeight("-1px");
        mainLayout.addComponent(richTextArea_1, "top:299.0px;left:98.0px;");

        // twinColSelect_1
        twinColSelect_1 = new TwinColSelect();
        twinColSelect_1.setImmediate(false);
        twinColSelect_1.setWidth("-1px");
        twinColSelect_1.setHeight("-1px");
        mainLayout.addComponent(twinColSelect_1, "top:40.0px;left:532.0px;");

        // button_1
        button_1 = new Button();
        button_1.setCaption("Button");
        button_1.setImmediate(true);
        button_1.setWidth("-1px");
        button_1.setHeight("-1px");
        mainLayout.addComponent(button_1, "top:120.0px;left:70.0px;");

        // table_1
        table_1 = new Table();
        table_1.setImmediate(false);
        table_1.setWidth("-1px");
        table_1.setHeight("-1px");
        mainLayout.addComponent(table_1, "top:240.0px;left:721.0px;");

        return mainLayout;
    }

}
